FROM orgoro/dlib-opencv-python

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV HOME=/app
RUN mkdir $HOME
WORKDIR $HOME

RUN mkdir $HOME/public
RUN mkdir $HOME/public/static
RUN mkdir $HOME/public/media
RUN mkdir $HOME/public/api-weights

# install system dependencies
RUN apt-get update && \
    apt install -y git \
                   ffmpeg libsm6 libxext6 \
                   poppler-utils \
                   python3-pip \
                   python3-opencv \
                   tesseract-ocr

RUN pip install --trusted-host pypi.python.org --upgrade pip

COPY requirements.dev.txt $HOME/requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY . .

ENTRYPOINT ["./entrypoint.sh"]
