# version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=backend.settings.prod
    volumes:
      - static:/app/public/static
      - media:/app/public/media
      - api_weights:/app/api-weights
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  database:
  api_weights:
  static:
  media: