# version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.dev
    image: violence-detector-backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/app/app
      - api_weights:/app/weights
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  database:
  api_storage:
  api_weights:
  static:
  media: